name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0.0-dev libudev-dev libhidapi-dev libfontconfig-dev

    - name: Rust Cache
      uses: swatinem/rust-cache@v2

    - name: Install cargo tools
      run: cargo install cargo-deb cargo-generate-rpm

    - name: Build
      run: cargo build --verbose --release

    - name: Get the version (git tag)
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Packages
      run: |
        strip -s target/release/led-name-badge
        cargo deb
        cargo generate-rpm

    - name: Upload Debian Package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/debian/led-name-badge_${{ steps.get_version.outputs.VERSION }}_amd64.deb
        asset_name: led-name-badge_${{ steps.get_version.outputs.VERSION }}_amd64.deb
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload RPM Package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/generate-rpm/led-name-badge-${{ steps.get_version.outputs.VERSION }}-1.x86_64.rpm
        asset_name: led-name-badge-${{ steps.get_version.outputs.VERSION }}-1.x86_64.rpm
        tag: ${{ github.ref }}
        overwrite: true
